### ISSUE TITLE
Support more types of comments

### ISSUE THREAD

**Issue by SirWindfield** [ProbablyClem/cargo-todo#4]
Hey!

Maybe you're interested in more types of comments. I usually use [this](https://github.com/aaron-bond/better-comments) VSCode extension for comment highlighting. It has a great variety :)
It actually lets you configure them yourself but the more common ones are `TODO`, `NOTE`, `FIXME`

**Comment by schulzch** [comment]
Don't forget //XXX (usually a heads up/implemented in a hacky way) and //HACK :)

**Comment by SirWindfield** [comment]
I actually didn't know what //XXX was meaning :smile: TIL.

@ProbablyClem maybe a config file in the long run might be a cool idea, or using `Cargo.toml` where you can define your own like `cargo-deb` for example:

```toml
[package.metadata.todo]
include = ["todo", "hack"]
custom = [
    ["<some regex to match>", "<name used to report in console>"],
    # ...
]
```
